### ISSUE TITLE
Level 8 Hammer? 

### ISSUE THREAD

**Issue by Doibi** [Syrikal/Tetranomicon#5]
Dragonsteel from Ice and fire requires a Tier 8 hammer 
but I don't know how to get that 
 
![image](https://user-images.githubusercontent.com/85194729/120380282-f8f8ec00-c2ee-11eb-85e0-8e0d7f4f78cd.png)

I have a forge hammer with two combustion chambers and it doesn't work it says tier 7

**Comment by CTH999** [comment]
It's now level 9 required!

**Comment by Syrikal** [comment]
This is intentional behavior. Some materials are sufficiently high level that not all parts can be made out of them.

If you'd like to change this, you can overwrite the dragonsteel materials using the datapack attached to 1.2 on CurseForge; reduce the 'requiredTools' numbers and the required hammer level will decrease.

**Comment by Wary282** [comment]
datapack where?

**Comment by VenomlessCZ** [comment]
playing on 1.19.2 and it requires level 10 - impossible even with toolboosters
